name: Upload Website

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./public/ s3://utopias3data/game --delete
